logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
  file:
    name: logs/server.log

spring:
  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      connection:
        CharSet: utf8mb4
    properties:
      hibernate.format_sql: true
